@startuml
skinparam classAttributeIconSize 0
hide circles

title Component-Level Description

abstract class Command {
    --
    +execute(tradeList, ui, storage)
}

class ListCommand {
    --
    +execute(tradeList, ui, storage)
}

class Ui <<boundary>> {
    +printTradeList(tradeList)
}

Command <|-- ListCommand
ListCommand ..> Ui : calls printTradeList()

note right of ListCommand::execute
  <b>Logic:</b>
  ui.printTradeList(tradeList)
end note

@enduml
