@startuml
hide footbox
skinparam Style strictuml
skinparam SequenceMessageAlign center

participant ":TradeLog" as TradeLog
participant "<<class>>\nParser" as Parser
participant "ac:AddCommand" as AddCommand
participant "<<class>>\nParserUtil" as ParserUtil
participant "t:Trade" as Trade
participant "tl:TradeList" as TradeList
participant ":Ui" as Ui

activate TradeLog

TradeLog -> Parser : parseCommand(...)
activate Parser
create AddCommand
Parser -> AddCommand : new AddCommand(arguments)
activate AddCommand
AddCommand --> Parser : ac
deactivate AddCommand
Parser --> TradeLog : ac
deactivate Parser

TradeLog -> AddCommand : execute(tradeList, ui, storage)
activate AddCommand

AddCommand -> ParserUtil : parseStrategy("BB")
activate ParserUtil
ParserUtil --> AddCommand : "Breakout"
deactivate ParserUtil

create Trade
AddCommand -> Trade : new Trade(..., "Breakout")
activate Trade
Trade --> AddCommand
deactivate Trade

AddCommand -> TradeList : addTrade(t)
activate TradeList
TradeList --> AddCommand
deactivate TradeList
AddCommand -> Ui : printTrade(t)
activate Ui
Ui --> AddCommand
deactivate Ui
AddCommand -> Ui : showTradeAdded()
activate Ui
Ui --> AddCommand
deactivate Ui
AddCommand --> TradeLog
deactivate AddCommand
deactivate TradeLog
@enduml
